version: '3'

services:
  app:
    build: .
    image: advent-app:latest
    container_name: advent-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST            : ${DB_HOST}
      DB_PORT            : ${DB_PORT}
      DB_USER            : ${DB_USER}
      DB_PASS            : ${DB_PASS}
      SECRET_KEY_BASE    : ${SECRET_KEY_BASE}
      FORTYTWO_KEY       : ${FORTYTWO_KEY}
      FORTYTWO_SECRET    : ${FORTYTWO_SECRET}
      SENTRY_DSN         : ${SENTRY_DSN}
      AOC_LEADERBOARD_ID : ${AOC_LEADERBOARD_ID}
      AOC_LOGIN_TOKEN    : ${AOC_LOGIN_TOKEN}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: advent-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB       : advent
      POSTGRES_USER     : ${DB_USER}
      POSTGRES_PASSWORD : ${DB_PASS}
    ports:
      - "5432:5432"

volumes:
  postgres_data: {}
